# Generated by Django 5.0.6 on 2024-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.IntegerField(choices=[(1, 'Merkado'), (2, 'Pepelitan')], null=True),
        ),
    ]
