# Generated by Django 3.2.6 on 2024-05-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.CharField(max_length=100)),
            ],
        ),
    ]
