# Generated by Django 5.0.6 on 2024-06-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_first_name', models.CharField(max_length=50)),
                ('operator_last_name', models.CharField(max_length=50)),
                ('operator_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qr_code', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('vhs', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, default='Unpaid', max_length=10, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.operator')),
            ],
        ),
    ]
