# Generated by Django 5.0.6 on 2024-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(blank=True, default='unpaid', max_length=10, null=True),
        ),
    ]
