# Generated by Django 3.2.6 on 2024-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vhs',
            field=models.CharField(blank=True, choices=[('Jeep', 'Jeep'), ('Multicab', 'Multicab'), ('Tricycle', 'Tricycle')], max_length=10, null=True),
        ),
    ]
