# Generated by Django 3.2.6 on 2024-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20240512_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vhs',
            field=models.CharField(blank=True, choices=[('1', 'Jeep'), ('2', 'Multicab'), ('3', 'Tricycle')], max_length=10, null=True),
        ),
    ]
