# Generated by Django 3.2.6 on 2024-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20240512_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
