# Generated by Django 3.2.6 on 2024-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vhs',
            field=models.CharField(blank=True, choices=[('1', 'Cab'), ('2', 'Tricycle')], max_length=10, null=True),
        ),
    ]
