# Generated by Django 5.0.6 on 2024-05-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_vhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
