# Generated by Django 5.0.6 on 2024-05-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_operator_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.operator'),
        ),
    ]
