# Generated by Django 5.0.6 on 2024-05-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_remove_operator_driver_driver_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='address',
            new_name='op_address',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='first_name',
            new_name='op_first_name',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='last_name',
            new_name='op_last_name',
        ),
    ]
