# Generated by Django 5.0.6 on 2024-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_rename_op_address_operator_operator_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vhs',
            field=models.IntegerField(default=1),
        ),
    ]
