# Generated by Django 5.0.6 on 2024-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverscan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='driverscan',
            name='action',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
