# Generated by Django 5.0.6 on 2024-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_driverscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverscan',
            name='endpoint',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
