# Generated by Django 5.0.6 on 2024-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_driverscan_amount_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverscan',
            name='endpoint',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
